name: CI
on:
  pull_request:
  push:
    branches: [ master ]
jobs:
  test:
    strategy:
      matrix:
        node: [ '0.8', '0.10', '0.12', '4', '6', '8', '10', '12', '14', latest ]
        os: [ ubuntu-latest, windows-latest ]
        script: [ compress, mocha, release/benchmark, release/jetstream ]
        exclude:
          - node: '0.8'
            script: release/benchmark
          - node: '0.8'
            script: release/jetstream
    name: ${{ matrix.node }} ${{ matrix.os }} ${{ matrix.script }}
    runs-on: ${{ matrix.os }}
    env:
      NODE: ${{ matrix.node }}
      TYPE: ${{ matrix.script }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: tmp
          key: tmp ${{ matrix.script }}
      - name: Perform tests
        shell: bash
        run: |
          . ./test/release/install.sh
          node test/$TYPE
