name: CI
on: [ push, pull_request ]
jobs:
  test:
    strategy:
      matrix:
        node: [ "0.10", "0.12", "4", "6", "8", "10", latest ]
        os: [ ubuntu-latest, windows-latest ]
        script: [ compress, mocha, release/benchmark, release/jetstream ]
    name: ${{ matrix.node }} ${{ matrix.os }} ${{ matrix.script }}
    runs-on: ${{ matrix.os }}
    env:
      NODE: ${{ matrix.node }}
      TYPE: ${{ matrix.script }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: tmp
          key: tmp ${{ matrix.script }}
      - name: Perform tests
        shell: bash
        run: |
          git clone --branch v1.5.4 --depth 1 https://github.com/jasongin/nvs.git ~/.nvs
          cd ~/.nvs
          . ./nvs.sh || { git clean -xdf && . ./nvs.sh; } || { git clean -xdf && . ./nvs.sh; }
          cd -
          nvs --version
          nvs add $NODE || nvs add $NODE || nvs add $NODE
          nvs use $NODE
          node --version
          npm config set audit false
          npm config set optional false
          npm config set save false
          npm config set update-notifier false
          npm --version
          npm install || npm install || npm install
          node test/$TYPE
