name: Fuzzing
on:
  schedule:
    - cron: "*/15 * * * *"
jobs:
  ufuzz:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Perform fuzzing
        shell: bash
        run: |
          git clone --branch v1.5.4 --depth 1 https://github.com/jasongin/nvs.git ~/.nvs
          cd ~/.nvs
          . ./nvs.sh || { git clean -xdf && . ./nvs.sh; } || { git clean -xdf && . ./nvs.sh; }
          cd -
          nvs --version
          nvs add 10 || nvs add 10 || nvs add 10
          nvs use 10
          node --version
          npm config set audit false
          npm config set optional false
          npm config set save false
          npm config set update-notifier false
          npm --version
          npm install || npm install || npm install
          node test/ufuzz/job 3600000
