name: Fuzzing
on:
  pull_request:
  schedule:
    - cron: '*/5 * * * *'
env:
  BASE_URL: https://api.github.com/repos/${{ github.repository }}
  CAUSE: ${{ github.event_name }}
  RUN_NUM: ${{ github.run_number }}
  TOKEN: ${{ github.token }}
jobs:
  ufuzz:
    strategy:
      fail-fast: false
      matrix:
        include:
          - node: latest
            os: macos-latest
          - node: '8'
            os: ubuntu-latest
          - node: '8'
            os: ubuntu-latest
          - node: '8'
            os: windows-latest
          - node: '8'
            os: windows-latest
    name: ${{ matrix.node }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      NODE: ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Perform fuzzing
        shell: bash
        run: |
          . ./test/release/install.sh
          if [[ $CAUSE == "schedule" ]]; then
            node test/ufuzz/job $BASE_URL $TOKEN $RUN_NUM
          else
            node test/ufuzz/job 5000
          fi
