name: Fuzzing
on:
  schedule:
    - cron: "*/15 * * * *"
jobs:
  ufuzz:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - shell: bash
        run: |
          git clone --branch v1.5.2 --depth 1 https://github.com/jasongin/nvs.git ~/.nvs
          . ~/.nvs/nvs.sh
          nvs --version
          nvs add node
          nvs use node
          node --version
          npm --version --no-update-notifier
          npm install --no-audit --no-optional --no-save --no-update-notifier
          node test/ufuzz/job 3600000
